name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build with Gradle
      run: echo "Gradle project simulated. Real build requires full Android project."
    - name: Simulate APK output
      run: |
        mkdir -p app/build/outputs/apk/debug
        echo "This is a dummy APK" > app/build/outputs/apk/debug/app-debug.apk
    - uses: actions/upload-artifact@v3
      with:
        name: PokerKing456-APK
        path: app/build/outputs/apk/debug/app-debug.apk
